name: GitHub Pages

on:
  push:
    branches:
    - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - run: python generate.py config.json output
    - uses: actions/upload-pages-artifact@v3
      with:
        path: output
    - uses: actions/deploy-pages@v4
